require 'hoe'
require './lib/computer/version.rb'

Hoe.spec 'computer' do

  self.version = Computer::VERSION

  self.summary = "computer gem  -  shell command line helper / wrapper 'n' more for your computer"
  self.description = summary

  self.urls    = { home: 'https://github.com/rubycoco/git' }

  self.author  = 'Gerald Bauer'
  self.email   = 'ruby-talk@ruby-lang.org'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = []

  self.licenses = ['Public Domain']

  self.spec_extras = {
   required_ruby_version: '>= 2.2.2'
  }

end
