require 'hoe'
require './lib/hubba/version.rb'

Hoe.spec 'hubba' do

  self.version = Hubba::VERSION

  self.summary = 'hubba - (yet) another (lite) GitHub HTTP API client / library'
  self.description = summary

  self.urls    = { home: 'https://github.com/rubycoco/hubba' }

  self.author  = 'Gerald Bauer'
  self.email   = 'ruby-talk@ruby-lang.org'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = []

  self.licenses = ['Public Domain']

  self.spec_extras = {
   required_ruby_version: '>= 2.3'
  }

end
