require 'hoe'
require './lib/commands-lite/version.rb'

Hoe.spec 'commands-lite' do

  self.version = CommandsLite::VERSION

  self.summary = "commands-lite gem - (lite) commands 'n' options helper / wrapper / parser / runner"
  self.description = summary

  self.urls    = { home: 'https://github.com/rubycoco/git' }

  self.author  = 'Gerald Bauer'
  self.email   = 'ruby-talk@ruby-lang.org'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = []

  self.licenses = ['Public Domain']

  self.spec_extras = {
   required_ruby_version: '>= 2.2.2'
  }

end
