require 'hoe'
require './lib/gitti/version.rb'

Hoe.spec 'gitti' do

  self.version = Gitti::VERSION

  self.summary = 'gitti - (yet) another (lite) git command line helper / wrapper'
  self.description = summary

  self.urls    = { home: 'https://github.com/rubycoco/gitti' }

  self.author  = 'Gerald Bauer'
  self.email   = 'ruby-talk@ruby-lang.org'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = []

  self.licenses = ['Public Domain']

  self.spec_extras = {
   required_ruby_version: '>= 2.2.2'
  }

end
