require 'hoe'
require './lib/yorobot/version.rb'

Hoe.spec 'yorobot' do

  self.version = Yorobot::Module::Tool::VERSION

  self.summary = "yorbot gem - yo, robot - automate, automate, automate - ready to use scripts and command line tool"
  self.description = summary

  self.urls    = { home: 'https://github.com/rubycoco/git' }

  self.author  = 'Gerald Bauer'
  self.email   = 'ruby-talk@ruby-lang.org'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = [
    ['flow-lite',     '>= 1.1.0'],
    ['gitti',         '>= 0.6.1'],
    ['hubba',         '>= 1.0.0'],
    ['hubba-reports', '>= 1.0.1'],
    ['monos',         '>= 1.1.1'],   ## todo/check: just add monofile - why? why not?
  ]

  self.licenses = ['Public Domain']

  self.spec_extras = {
   required_ruby_version: '>= 2.2.2'
  }

end
