require 'hoe'
require './lib/hubba/reports/version.rb'

Hoe.spec 'hubba-reports' do

  self.version = HubbaReports::VERSION

  self.summary = 'hubba-reports - auto-generate github statistics / analytics reports from github api data (stars, timeline, traffic, top pages, top referrers, etc.)'
  self.description = summary

  self.urls    = { home: 'https://github.com/rubycoco/git' }

  self.author  = 'Gerald Bauer'
  self.email   = 'ruby-talk@ruby-lang.org'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = [
    ['hubba', '>= 1.0.0']
  ]

  self.licenses = ['Public Domain']

  self.spec_extras = {
   required_ruby_version: '>= 2.2.2'
  }

end
