require 'hoe'

Hoe.spec 'monofile' do

  self.version = '0.0.1'   # note: for now add version inline

  self.summary = "monofile - read in/ parse mono (source) tree defintions with git (and github) projects, and more"
  self.description = summary

  self.urls = { home: 'https://github.com/rubycoco/git' }

  self.author = 'Gerald Bauer'
  self.email = 'opensport@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']

  self.extra_deps = []

  self.spec_extras = {
    required_ruby_version: '>= 2.2.2'
  }
end
